use_frameworks!

platform :ios, '11.0'

target 'WDBaseLib_Example' do
  pod 'WDBaseLib', :path => '../'

  target 'WDBaseLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
